import enum

class AssetType(str, enum.Enum):
    BRIDGE = "BRIDGE"
    TUNNEL = "TUNNEL"
    HIGHWAY = "HIGHWAY"
    CULVERT = "CULVERT"

class BridgeType(str, enum.Enum):
    BEAM = "BEAM"
    ARCH = "ARCH"
    TRUSS = "TRUSS"
    SLAB = "SLAB"
    SUSPENSION = "SUSPENSION"
    CABLE_STAYED = "CABLE_STAYED"
    CANTILEVER = "CANTILEVER"
    BOX_GIRDER = "BOX_GIRDER"
    OTHER = "OTHER"

class StructureCategory(str, enum.Enum):
    CULVERT = "CULVERT"
    MINOR = "MINOR"
    MAJOR = "MAJOR"
    EXTRA_LONG = "EXTRA_LONG"

class BridgeStatus(str, enum.Enum):
    PLANNED = "PLANNED"
    UNDER_CONSTRUCTION = "UNDER_CONSTRUCTION"
    OPERATIONAL = "OPERATIONAL"
    UNDER_MAINTENANCE = "UNDER_MAINTENANCE"
    UNDER_REHABILITATION = "UNDER_REHABILITATION"
    CLOSED = "CLOSED"
    DECOMMISSIONED = "DECOMMISSIONED"

class InspectionType(str, enum.Enum):
    ROUTINE = "ROUTINE"
    PRINCIPAL = "PRINCIPAL"
    EMERGENT = "EMERGENT"
    UNDERWATER = "UNDERWATER"
    SPECIAL = "SPECIAL"

class InspectionStatus(str, enum.Enum):
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"

class ComponentType(str, enum.Enum):
    DECK = "DECK"
    SUPERSTRUCTURE = "SUPERSTRUCTURE"
    SUBSTRUCTURE = "SUBSTRUCTURE"
    FOUNDATION = "FOUNDATION"
    BEARINGS = "BEARINGS"
    EXPANSION_JOINTS = "EXPANSION_JOINTS"
    APPROACHES = "APPROACHES"
    DRAINAGE = "DRAINAGE"
    SAFETY_BARRIERS = "SAFETY_BARRIERS"
    SCOUR_RIVERBED = "SCOUR_RIVERBED"
    WATERWAY = "WATERWAY"
    # Tunnel components
    TUNNEL_LINING = "TUNNEL_LINING"
    TUNNEL_CROWN = "TUNNEL_CROWN"
    TUNNEL_INVERT = "TUNNEL_INVERT"
    TUNNEL_VENTILATION = "TUNNEL_VENTILATION"
    TUNNEL_LIGHTING = "TUNNEL_LIGHTING"
    TUNNEL_FIRE_SAFETY = "TUNNEL_FIRE_SAFETY"
    # Highway components
    PAVEMENT_SURFACE = "PAVEMENT_SURFACE"
    ROAD_BASE = "ROAD_BASE"
    SHOULDERS = "SHOULDERS"
    ROAD_DRAINAGE = "ROAD_DRAINAGE"
    ROAD_MARKINGS = "ROAD_MARKINGS"
    # Culvert components
    CULVERT_BARREL = "CULVERT_BARREL"
    CULVERT_HEADWALL = "CULVERT_HEADWALL"
    CULVERT_WINGWALL = "CULVERT_WINGWALL"
    CULVERT_APRON = "CULVERT_APRON"
    CULVERT_SILT_TRAP = "CULVERT_SILT_TRAP"

class ConditionCategory(str, enum.Enum):
    EXCELLENT = "EXCELLENT"
    GOOD = "GOOD"
    FAIR = "FAIR"
    POOR = "POOR"
    CRITICAL = "CRITICAL"

class DefectSeverity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class MaintenanceType(str, enum.Enum):
    ROUTINE = "ROUTINE"
    PREVENTIVE = "PREVENTIVE"
    REPAIR = "REPAIR"
    REHABILITATION = "REHABILITATION"
    STRENGTHENING = "STRENGTHENING"
    EMERGENCY_REPAIR = "EMERGENCY_REPAIR"
    RECONSTRUCTION = "RECONSTRUCTION"

class MaintenancePriority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class MaintenanceStatus(str, enum.Enum):
    REPORTED = "REPORTED"
    APPROVED = "APPROVED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    VERIFIED = "VERIFIED"
    CANCELLED = "CANCELLED"

class LifecycleEventType(str, enum.Enum):
    PROPOSED = "PROPOSED"
    SURVEYED = "SURVEYED"
    DESIGNED = "DESIGNED"
    APPROVED = "APPROVED"
    TENDERED = "TENDERED"
    CONSTRUCTION_STARTED = "CONSTRUCTION_STARTED"
    CONSTRUCTION_COMPLETED = "CONSTRUCTION_COMPLETED"
    COMMISSIONED = "COMMISSIONED"
    INSPECTION_COMPLETED = "INSPECTION_COMPLETED"
    MAINTENANCE_STARTED = "MAINTENANCE_STARTED"
    MAINTENANCE_COMPLETED = "MAINTENANCE_COMPLETED"
    REPAIR_STARTED = "REPAIR_STARTED"
    REPAIR_COMPLETED = "REPAIR_COMPLETED"
    REHABILITATION_STARTED = "REHABILITATION_STARTED"
    REHABILITATION_COMPLETED = "REHABILITATION_COMPLETED"
    CLOSED = "CLOSED"
    REOPENED = "REOPENED"
    DECOMMISSIONED = "DECOMMISSIONED"

class DocumentType(str, enum.Enum):
    DESIGN_DRAWING = "DESIGN_DRAWING"
    STRUCTURAL_DRAWING = "STRUCTURAL_DRAWING"
    INSPECTION_REPORT = "INSPECTION_REPORT"
    MAINTENANCE_REPORT = "MAINTENANCE_REPORT"
    CONTRACT = "CONTRACT"
    CERTIFICATE = "CERTIFICATE"
    PHOTOGRAPH = "PHOTOGRAPH"
    VIDEO = "VIDEO"
    OTHER = "OTHER"

class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    DEPARTMENT_HEAD = "DEPARTMENT_HEAD"
    EXECUTIVE_ENGINEER = "EXECUTIVE_ENGINEER"
    INSPECTOR = "INSPECTOR"
    MAINTENANCE_OFFICER = "MAINTENANCE_OFFICER"
    VIEWER = "VIEWER"

class OperationalStatus(str, enum.Enum):
    OPERATIONAL = "OPERATIONAL"
    PARTIALLY_CLOSED = "PARTIALLY_CLOSED"
    CLOSED = "CLOSED"
    UNDER_MAINTENANCE = "UNDER_MAINTENANCE"
    UNDER_REHABILITATION = "UNDER_REHABILITATION"
